# Start with the official Alpine image
FROM alpine:3.23.3

# Set environment variables
# https://docs.renovatebot.com/modules/datasource/github-releases/
# Renovate definition: datasource=github-releases depName=etcd-io/etcd
ENV ETCD_VERSION=v3.6.8
ENV ETCD_BINARIES_URL=https://github.com/etcd-io/etcd/releases/download

# Install necessary dependencies
RUN apk add --no-cache \
    curl \
    bash \
    && rm -rf /var/cache/apk/*

# Determine architecture and download appropriate etcdctl binary
RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "x86_64" ]; then \
        ETCD_ARCH="amd64"; \
    elif [ "$ARCH" = "aarch64" ]; then \
        ETCD_ARCH="arm64"; \
    else \
        echo "Unsupported architecture: $ARCH" && exit 1; \
    fi && \
    curl -L "${ETCD_BINARIES_URL}/${ETCD_VERSION}/etcd-${ETCD_VERSION}-linux-${ETCD_ARCH}.tar.gz" -o /tmp/etcd.tar.gz && \
    tar -xzvf /tmp/etcd.tar.gz -C /tmp && \
    mv /tmp/etcd-${ETCD_VERSION}-linux-${ETCD_ARCH}/etcdctl /usr/local/bin/ && \
    rm -rf /tmp/etcd-${ETCD_VERSION}-linux-${ETCD_ARCH} /tmp/etcd.tar.gz

# Set default entrypoint (can be customized based on usage)
ENTRYPOINT ["etcdctl"]
