---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  ports:
    - name: client
      port: {{ include "etcd.clientPort" . }}
      targetPort: client
      protocol: TCP
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
