{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- include "secrets.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .namespace .name }}
  {{- range $key, $length := .keys }}
  {{- if and $existingSecret (hasKey $existingSecret.data $key) }}
  {{ $key }}: {{ index $existingSecret.data $key }}
  {{- else }}
  {{ $key }}: {{ randAlphaNum ($length | int) | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
