---
# Changes here will be overwritten by Copier.
_commit: 331b26b
_src_path: ..
componentName: Keycloak
componentSlug: keycloak
releases: app,config
shortDescription: Central identity management of the platform
