repositories:
  - name: frost
    url: https://kernblick.github.io/helm-charts-snapshot/

releases:
  - name: frost
    namespace: frost
    createNamespace: true
    chart: frost/frost-server
    version: 2.5.1
    wait: true
    waitRetries: 3
    waitForJobs: true
    timeout: 60
    values:
      - values/frost.yaml
      - frost:
          auth:
            keycloakConfigUrl: "keycloak-api.keycloak.svc.cluster.local/auth/realms/admin/clients-registrations/install/abcdef"
            keycloakConfigSecret: "abcdef"
          http:
            image:
              tag: 2.6.0
            serviceHost: frost-api.frost.svc.cluster.local
            urlSubPath: "FROST-Server"
          mqtt:
            image:
              tag: 2.6.0
          db:
            enableIntegratedDb: false
            host: postgresql.postgresql.svc.cluster.local
            dbExternalConnectionString: jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/frost
            existingSecret: frost-db-credentials
            usernameKey: username
            passwordKey: password
          bus:
            image:
              tag: 2.0.22
