{{- if and .Values.registry.enabled .Values.registry.ui.enabled .Values.registry.ui.ingress.enabled .Values.registry.ui.ingress.host -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "apicurio.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apicurio.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  {{- with .Values.registry.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.registry.ui.ingress.ingressClassName }}
  ingressClassName: {{ .Values.registry.ui.ingress.ingressClassName }}
  {{- end }}
  rules:
  - host: {{ .Values.registry.ui.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "apicurio.fullname" . }}-ui
            port:
              name: http
  {{- if .Values.registry.ui.ingress.tls }}
  tls:
    {{- toYaml .Values.registry.ui.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
