---
# Changes here will be overwritten by Copier.
_commit: v2.0-beta
_src_path: https://gitlab.com/civitas-connect/civitas-core/civitas-core-v2/civitas-core-deployment
componentName: Grafana
componentSlug: grafana
releases: grafana
shortDescription: Analytics and visualization dashboards
