services:
  garage:
    image: dxflrs/garage:v2.1.0
    container_name: garage
    hostname: garage
    environment:
      RUST_LOG: garage=debug
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
    volumes:
      - data:/var/lib/garage/data
      - meta:/var/lib/garage/meta
    configs:
      - source: garage-config
        target: /etc/garage.toml

  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    configs:
      - source: garage-config
        target: /app/config/garage.toml
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"

volumes:
  data:
  meta:

configs:
  garage-config:
    content: |
      metadata_dir = "/var/lib/garage/meta"
      data_dir = "/var/lib/garage/data"
      replication_factor = 1
      rpc_bind_addr = "[::]:3901"
      rpc_secret = "84B026197D42744980A7332F9F58285D69D7DE7DE240466994B3A1566CAA385F"
      bootstrap_peers = []
      [s3_api]
      s3_region = "berlin"
      api_bind_addr = "[::]:3900"
      bind_addr = "[::]:3900"
      [s3_web]
      bind_addr = "[::]:3902"
      root_domain = "localhost"
      index = "index.html"
