---
# Changes here will be overwritten by Copier.
_commit: 9796c60
_src_path: https://gitlab.com/civitas-connect/civitas-core/civitas-core-v2/civitas-core-deployment.git
componentName: Kafka
componentSlug: kafka
releases: operator,cluster,ui
shortDescription: Asynchronous central message broker for interservice communication
