---
# Changes here will be overwritten by Copier.
_commit: '5450213'
_src_path: /home/julian/projects/civitas/civitas-2/template-component
componentName: Kafka
componentSlug: kafka
helmChartName: oci://quay.io/strimzi-helm/strimzi-kafka-operator
helmRepository: https://kafbat.github.io/helm-charts
shortDescription: Asynchronous central message broker for interservice communication
