---
# Changes here will be overwritten by Copier.
_commit: 6fd161f
_src_path: ..
componentName: Kafka
componentSlug: kafka
releases: operator,cluster,ui
shortDescription: Asynchronous central message broker for interservice communication
