{{- if .Values.connect.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: {{ .Values.connect.name | default (printf "%s-connect" (include "kafka.clusterName" .)) }}
  labels:
    strimzi.io/cluster: {{ include "kafka.clusterName" . }}
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.connect.replicas | default 1 }}
  {{- if .Values.connect.image }}
  image: {{ .Values.connect.image | quote }}
  {{- end }}
  bootstrapServers: {{ .Values.connect.bootstrapServers | default (printf "%s-kafka-bootstrap:9092" (include "kafka.clusterName" .)) | quote }}
  config:
    {{- toYaml .Values.connect.config | nindent 4 }}
  {{- with .Values.connect.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

