{{- range $i, $t := .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $t.name }}
  labels:
    strimzi.io/cluster: {{ include "kafka.clusterName" $ }}
    {{- include "kafka.labels" $ | nindent 4 }}
spec:
  partitions: {{ $t.partitions | default 3 }}
  replicas: {{ $t.replicas | default 3 }}
  {{- with $t.config }}
  config:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
