apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controllers
  labels:
    strimzi.io/cluster: {{ include "kafka.clusterName" . }}
spec:
  replicas: {{ .Values.controller.replicas }}
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 10Gi
    deleteClaim: false
  {{- if .Values.controller.resources }}
  resources:
{{ toYaml .Values.controller.resources | nindent 4 }}
  {{- end }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: brokers
  labels:
    strimzi.io/cluster: {{ include "kafka.clusterName" . }}
spec:
  replicas: {{ .Values.broker.replicas }}
  roles:
    - broker
  config:
    num.network.threads: 3
    num.io.threads: 8
    num.replica.fetchers: 2
    log.retention.ms: 2592000000  # 30d default
    queued.max.requests: 500
  storage:
    type: persistent-claim
    size: 5Gi
    deleteClaim: false
  {{- if .Values.broker.resources }}
  resources:
{{ toYaml .Values.broker.resources | nindent 4 }}
  {{- end }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "kafka.clusterName" . }}
spec:
  kafka:
    version: 4.1.0
    metadataVersion: 4.1-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
