---
# Changes here will be overwritten by Copier.
_commit: 6fe9433
_src_path: ..
componentName: Postgres
componentSlug: postgres
releases: operator, cluster
shortDescription: Central managed PostgreSQL database for Civitas platform
