---
portalBE:
  name: Portal Backend
  description: Portal Backend API Service
  upstream: portal-portal-backend:8080
  uri: /v2/*
portalBFF:
  name: Portal BFF
  description: Backend-for-Frontend for the Civitas Portal
  upstream: portal-portal-frontend:3000
  subDomain: portal
  uri: /*
