{{- if .Values.linkerd.enabled }}
{{ .Files.Get "files/require-linkerd-sidecar.yaml" | replace "KYVERNO_FAILURE_ACTION" .Values.failureAction }}
{{ .Files.Get "files/require-meshed-namespace-inbound-policy.yaml" | replace "KYVERNO_FAILURE_ACTION" .Values.failureAction }}
{{ .Files.Get "files/justify-linkerd-inject-opt-out.yaml" | replace "KYVERNO_FAILURE_ACTION" .Values.failureAction }}
{{- end }}
