{{- if .Values.operators.enabled }}
{{- $strimziUser := printf "system:serviceaccount:%s:strimzi-cluster-operator" (.Values.strimziOperatorNamespace | default .Release.Namespace) }}
{{- $cnpgUser := printf "system:serviceaccount:%s:postgres-operator-cloudnative-pg" (.Values.cnpgOperatorNamespace | default .Release.Namespace) }}
{{ .Files.Get "files/protect-operator-owned-labels.yaml" | replace "KYVERNO_FAILURE_ACTION" .Values.failureAction | replace "STRIMZI_OPERATOR_USERNAME" $strimziUser | replace "CNPG_OPERATOR_USERNAME" $cnpgUser }}
{{ .Files.Get "files/restrict-cnpg-operator-pod-labels.yaml" | replace "KYVERNO_FAILURE_ACTION" .Values.failureAction }}
{{ .Files.Get "files/restrict-strimzi-operator-pod-labels.yaml" | replace "KYVERNO_FAILURE_ACTION" .Values.failureAction }}
{{- end }}
