---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authz.fullname" . }}-opa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authz.opa.labels" . | nindent 4 }}
  {{- with .Values.opa.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.opa.service.type | default "ClusterIP" }}
  {{- with .Values.opa.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .Values.opa.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.opa.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.opa.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
  - port: {{ .Values.opa.service.port | default 8181 }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "authz.opa.selectorLabels" . | nindent 4 }}
