---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authz.fullname" . }}-opa-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authz.opa.labels" . | nindent 4 }}
data:
  opa-config.json: |
    {
      "authz_repository_url": "http://{{ include "authz.fullname" . }}-authz:{{ .Values.authz.service.port }}/api/v1/user-context",
      "authz_cache_duration_seconds": 0
    }
