---
# Changes here will be overwritten by Copier.
_commit: e167757
_src_path: ..
componentName: networkpolicies
componentSlug: networkpolicies
releases: networkpolicies
shortDescription: Network Polocies
