[ ca ]
default_ca             = default_ca

[ default_ca ]
dir                    = ./                  # Base directory for files
certs                  = certs               # Where the issued certs are kept
crl_dir                = crl                 # Where the issued CRLs are kept
database               = index.txt           # Database index file
crlnumber              = crlnumber           # CRL number file
crl                    = civitas.crl         # CRL output file
crl_extensions         = crl_ext             # Extensions for the CRL
default_crl_days       = 365                 # Validity of the CRL in days
default_md             = sha256              # Default message digest
x509_extensions        = ca_extensions       # Extensions for issued certs

[ crl_ext ]
# issuerAltName        = issuer:copy         # Copies the issuer name to AltName
authorityKeyIdentifier = keyid:always        # Include authority key identifier

[ ca_extensions ]
basicConstraints       = CA:true             # Indicates this is a CA cert
subjectKeyIdentifier   = hash                # Include subject key identifier
authorityKeyIdentifier = keyid:always        # Include authority key identifier
keyUsage               = critical, cRLSign, digitalSignature, keyCertSign
extendedKeyUsage       = serverAuth          # For server authentication
crlDistributionPoints  = URI:http://${DOMAIN}/civitas.crl

[ alt_names ]
DNS.1                  = ${DOMAIN}        # Primary domain
DNS.2                  = *.${DOMAIN}      # Wildcard domain
