---
# Changes here will be overwritten by Copier.
_commit: 0359c94
_src_path: .
componentName: Secrets
componentSlug: secrets
releases: generator
shortDescription: Generating secrets for components which expect pre configured secrets
  like admin passwords
