# Default values for secrets chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secrets: []
# Example:
# secrets:
#   - name: my-secret
#     namespace: default
#     keys:
#       password: 32
#       api-key: 64
