FROM alpine:3.23.3 AS fetcher

ARG TARGETARCH

# TODO: Add renovate definitions for these versions
# https://docs.renovatebot.com/modules/datasource/github-releases/
ENV HELM_VERSION=v4.1.0
ENV HELMFILE_VERSION=v1.2.3
ENV KUBECTL_VERSION=v1.35.0

# Install dependencies
RUN apk update && \
  apk add --no-cache \
  git \
  bash \
  curl

# Install kubectl
RUN curl -fL "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl" -o /tmp/kubectl
RUN chmod +x /tmp/kubectl

# Install Helm
RUN curl -fL "https://get.helm.sh/helm-${HELM_VERSION}-linux-${TARGETARCH}.tar.gz" -o /tmp/helm.tar.gz
RUN tar -xzf /tmp/helm.tar.gz -C /tmp

# Install helmfile
RUN curl -fL "https://github.com/helmfile/helmfile/releases/download/${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION#v}_linux_${TARGETARCH}.tar.gz" -o /tmp/helmfile.tar.gz
RUN tar -xzf /tmp/helmfile.tar.gz -C /tmp

FROM alpine:3.23.3 AS cicd

ARG TARGETARCH

# Get binaries from fetcher stage
COPY --from=fetcher /tmp/linux-${TARGETARCH}/helm /usr/local/bin/helm
COPY --from=fetcher /tmp/helmfile /usr/local/bin/helmfile
COPY --from=fetcher /tmp/kubectl /usr/local/bin/kubectl

# Install any additional dependencies needed for CI/CD tasks
RUN apk add --no-cache --update \
  git \
  python3 \
  py3-pip \
  nodejs \
  npm \
  bash \
  curl

# Install pre-commit
RUN pip install --break-system-packages pre-commit
