---
environments:
  default:
    values:
      - ../../environments/default/*.yaml
      - ../../environments/default/*.yaml.gotmpl
      - ../../environments/default/components/*.yaml.gotmpl
  testing:
    values:
      # default
      - ../../environments/default/*.yaml
      - ../../environments/default/*.yaml.gotmpl
      - ../../environments/default/components/*.yaml.gotmpl

      # testing
      - ../../environments/testing/*.yaml.gotmpl
      - ../../environments/testing/components/*.yaml.gotmpl
    missingFileHandler: Warn
  production:
    values:
      - environments/default/*.yaml
      - environments/production/*.yaml
