---
environments:
  default:
    values:
      - profile: local
      - ../../locks/*.lock.yaml
      - ../../environments/default/*.yaml
      - ../../environments/default/*.yaml.gotmpl
  testing:
    values:
      - profile: local
      - ../../locks/*.lock.yaml
      - ../../environments/default/*.yaml
      - ../../environments/default/*.yaml.gotmpl
      - ../../environments/testing/*.yaml.gotmpl
  production:
    values:
      - environments/default/*.yaml
      - environments/production/*.yaml
      - profile: large
