---
networkPolicy:
  enabled: false
  # Labels to select the CNPG cluster pods
  podSelector:
    cnpg.io/cluster: postgres-cluster
  # List of pod selectors allowed to reach Postgres.
  # Each entry becomes a separate `from` item in the ingress rule.
  ingressFrom:
    - app.kubernetes.io/name: cloudnative-pg
    - app.kubernetes.io/name: portal
      app.kubernetes.io/component: backend
    - app.kubernetes.io/instance: keycloak-app
    - app.kubernetes.io/name: authz-repo
    # - app.kubernetes.io/name: frost        # not yet deployed
    # - strimzi.io/cluster: kafka-cluster    # TBD
