---
# Values for Strimzi-based Kafka cluster

# Kafka cluster identity
clusterName: kafka-cluster
kafkaVersion: 4.1.0

controller:
  replicas: 1
  resources:
    requests:
      cpu: '500m'
      memory: '1Gi'
    limits:
      cpu: '1'
      memory: '2Gi'

broker:
  replicas: 1
  resources:
    requests:
      cpu: '500m'
      memory: '2Gi'
    limits:
      cpu: '2'
      memory: '4Gi'

kafka:
  # Listener presets; adjust as needed
  listeners:
    - name: internal
      port: 9092
      type: internal
      tls: true
    - name: external
      port: 9094
      type: nodeport
      tls: true
      configuration:
        bootstrap:
          nodePort: null
        brokers: []
  config: {} # we gradually add more default configs here

# Optional topics to create
# topics:
#   - name: example
#     partitions: 12
#     replicas: 3
#     config:
#       retention.ms: 604800000
#       cleanup.policy: delete

topics: []

# Optional users to create
# users:
#   - name: my-app
#     authentication:
#       type: tls
#     authorization:
#       type: simple
#       acls:
#         - resource:
#             type: topic
#             name: my-topic
#             patternType: literal
#           operation: Read
#         - resource:
#             type: group
#             name: my-group
#             patternType: literal
#           operation: Read
users: []
