---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: client
      port: {{ include "etcd.clientPort" . }}
      targetPort: client
      protocol: TCP
    - name: peer
      port: {{ include "etcd.peerPort" . }}
      targetPort: peer
      protocol: TCP
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
