---
apiVersion: v2
name: secrets
description: A Helm chart for generating and managing application secrets
icon: https://gitlab.com/uploads/-/system/group/avatar/78954426/CIVITASCORE_Icon.png?width=128
type: application
version: 0.1.0
appVersion: '1.0'
