apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-connect-streams
  namespace: {{ .Release.Namespace }}
data:
{{- if .Values.streams }}
{{- range $name, $config := .Values.streams }}
  {{ $name }}.yaml: |
    {{ $config | nindent 4 }}
{{- end }}
{{- else }}
  {}
{{- end }}
