{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- include "secrets.labels" $ | nindent 4 }}
  annotations:
    {{- include "secrets.annotations" $ | nindent 4 }}
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .namespace .name }}
  {{- range $key, $value := .keys }}
    {{- if and $existingSecret (hasKey $existingSecret.data $key) }}
  {{ $key }}: {{ index $existingSecret.data $key }}
    {{- else }}
      {{- if kindIs "map" $value }}
        {{- if eq (index $value "encoding" | default "") "hex" }}
  {{ $key }}: {{ printf "%x" (b64dec (randBytes (int (div ($value.length | int) 2)))) | b64enc | quote }}
        {{- else }}
  {{ $key }}: {{ randAlphaNum ($value.length | int) | b64enc | quote }}
        {{- end }}
      {{- else if kindIs "float64" $value }}
  {{ $key }}: {{ randAlphaNum ($value | int) | b64enc | quote }}
      {{- else }}
  {{ $key }}: {{ $value | b64enc | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
