{{- if .Values.database.createSecret.enabled | default true  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.createSecret.name | default (printf "%s-db-secret" .Values.database.name) }}
  labels:
    cnpg.io/reload: "true"
    {{- include "database.labels" . | nindent 4 }}
  {{- with .Values.database.createSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  username: {{ .Values.database.createSecret.username | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
type: kubernetes.io/basic-auth
{{- end }}